### ISSUE TITLE
ACEScct to ACES spec vs code discrepancy

### ISSUE THREAD

**Issue by RikshaDriver** [ampas/aces-dev#114]
So in the ACEScct spec S-2016-001, it stipulates that in the ACEScct to ACES transform

for any value `>= ( log2 (HALF_MAX) + 9.72 ) / 17.52`

the output must be = HALF_MAX (i.e. 65504)

The code is slightly different however:

```
float ACEScct_to_lin( input varying float in)
{
    if (in > Y_BRK)
        return pow( 2., in*17.52-9.72);
    else
        return (in - B) / A;
}
```

So is the spec wrong or does the  code need to be updated?

**Comment by scottdyer** [comment]
The CTL assumes that data is already limited to HALF_MAX (since the input is ACES2065-1). ACES2065-1 data cannot exceed 65504 - thus the spec is technically correct. Data is undefined there, so it must become equal to the endpoint of the function.
The logic says that if `in > Y_BRK`, then return `pow( 2., in*17.52-9.72);` 
`in` cannot exceed 65504, so I believe this is consistent with Equation 3 in S-2016-001.

**Comment by RikshaDriver** [comment]
Thanks for clarifying. Issue can be closed.
