### ISSUE TITLE
Specifications and Technical Bulletins should be individually available at a dedicated url for easier access and citation.

### ISSUE THREAD

**Issue by KelSolaar** [ampas/aces-dev#49]
Right now the various documents are all aggregated together in a zip file available as a link from this file in the repository: https://github.com/ampas/aces-dev/tree/master/documents

I think they should be directly in the repository and versioned like the code, their access would be easier and it would especially make citations a lot more easier.

**Comment by aforsythe** [comment]
Thomas,

We didn't add the PDFs to the repository because they are binary files.  In general adding binaries to source control isn't optimal.  We bounced around some ideas for future document source control and distribution mechanisms while we were working on v1.0 but we decided to tackle it post release.

Alex



[Δ]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>




>On Dec 28, 2014, at 2:20 AM, Thomas Mansencal <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now the various documents are all aggregated together in a zip file available as a link from this file in the repository: https://github.com/ampas/aces-dev/tree/master/documents

I think they should be directly in the repository and versioned like the code, their access would be easier and it would especially make citations a lot more easier.

**Comment by KelSolaar** [comment]
Hi Alex,

You don't really have anything significant binary wise, it is like a dozen documents for under 2mb, a tremendous amount of projects are storing images for instance (splashscreens, icons, screenshots for documentation) without any particular issue. A single splashscreen tailored for a retina screen can be bigger than the entire document directory. I wouldn't really worry about that.

Thomas

**Comment by st599** [comment]
In various documents I've read, AMPAS S-2014-2006 is referenced but isn't available in documents.zip.  Is it available on the web somewhere?
