### ISSUE TITLE
Dead link for reference images

### ISSUE THREAD

**Issue by epiil** [ampas/aces-dev#56]
The link for reference images found at https://www.dropbox.com/sh/lj9x6cyd5t56tha/AACmQNROIc2kNIg5e1snnhg2a?dl=0 is 404 / not found.

**Comment by aforsythe** [comment]
@epiil Thanks for adding the issue.  It has already been resolved on the [dev branch](https://github.com/ampas/aces-dev/blob/dev/images/README.md) with [93eb34b](https://github.com/ampas/aces-dev/commit/93eb34bcf39c253faeb0cacd737d73b9ff7da073#diff-30be2fd496ec9ace14468522cd541cda).  We will close this issue when the fix is rolled into the master.

**Comment by epiil** [comment]
Ah, I see now. Thanks!

**Comment by scottdyer** [comment]
Active link is now merged into the master from the dev as part of the 1.0.1 patch release.
