### ISSUE TITLE
Reference images folders are lowercase in Dropbox zip file

### ISSUE THREAD

**Issue by selfshadow** [ampas/aces-dev#68]
This is a nitpick, but the reference images zip file that's hosted on Dropbox contains some lowercase folder names: "aces", "lmt", "oces", "odt", "rrt". These don't match the uppercase Dropbox folders, which are also listed in images/README.md.

**Comment by scottdyer** [comment]
Hi @selfshadow 
I am having difficulty confirming this on my end. Can you confirm that this your issue is still the case?
Whenever I follow the Dropbox link in the images/README the folders are appropriately uppercase as designated in the README.

**Comment by selfshadow** [comment]
It's just the contents of the .zip file. I'm guessing that this is a quirk of Dropbox's zip procedure, where all-uppercase names get converted to lowercase for some reason.

**Comment by scottdyer** [comment]
Cleaning up old issues...
This was a quirk of Dropbox that I believe has since been fixed (sometime in the past 4+ years 😬). 
At least in my recent testing, downloading the directories from Dropbox appears to maintain the casing of the directory names. (on Mac OS 10.15.2)
If this is still an issue, please feel free to reopen or resubmit. 
Thanks!
