### ISSUE TITLE
v1.01 and v1.03_beta2 Utilities

### ISSUE THREAD

**Issue by scoopxyz** [ampas/aces-dev#94]
Was there an explanation as to the difference in utility naming convention between **v1.0.1** and **v1.0.3_beta2**?

e.g. post-rename:
**v1.0.1**: `ACESlib.Adjust_Exposure.a1.0.1.ctl`
**v1.0.3_beta2**: `ACESutil.Adjust_Exposure.a1.0.3.ctl` 

The CTL transform's seem to still be expecting the previous naming convention (_lib_ not _util_)

**v1.0.3_beta2** also appears to be missing the utilities:

- Utilities
- Transform_Common
- ODT_Common
- Tonescales

Are these assumed to be carried over from the prior version?

**Comment by scottdyer** [comment]
See commit 583f42746d6b34186877995b9b7c266b795c5a1e

Utilities were moved to a "lib" subdirectory and utility files were renamed from _ACESlib_ to _ACESutil_.

I believe all import statements are appropriately updated - I've been successfully testing and running CTL w/ versions up to v1.0.3_beta2 since this commit in November. If you do find any broken import statements after checking out the head of the v1.0.3_beta2 branch, please let me know.

**Comment by scoopxyz** [comment]
Ah great, I must have just skipped right over that directory. Thanks for the commit link.
